PXB-2243 handle undo truncation in incremental backup
rahulmalik87/percona-xtrabackup pull request #2
Opened 2020-07-30 08:28 UTC by rahulmalik87

Problem:
Undo files because unusable if truncation happens between backup and increment and there are pending redo on page 0
Analysis:
As part of 8.0.21, undo truncation is done by dropping and creating tablespace.
in the prior version it as done through drop and create undo file.
(see upstream WL#11819: Support ACID Undo DDL)
By just recreating the undo file instead of complete undo tablespace
Undo file doesn't have the latest space_id.
Fix:
if undo is truncated between the backup and increment. recreate tablespace by calling fil_space_create

2020-07-30 11:19 UTC, satya-bodapati requested changes
Please check suggested bug commit message and fix from JIRA.

Use it for github description and the commit message as well. 
Change the title as well

Also paste the output of failing testcase before and after fix

And also Jenkins link

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +@return space_id or SPACE_UNKOWN */
```suggestion

/* Retreive space_id from page 0 of tablespace
@param[in] file_name tablespace file path
@return space_id or SPACE_UNKOWN */
```

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +    const char *file_name /*!<in: file name */) {
```suggestion
    const char *file_name) {
```

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +    const char *file_name /*!<in: file name */) {
or entire thing in one line if it fits

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +        request, dict_sys_t::s_dd_space_file_name, file, page, UNIV_PAGE_SIZE);
This proves filename is irrelevant once file is opened.. Only used for printing filename in error messages

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +        request, dict_sys_t::s_dd_space_file_name, file, page, UNIV_PAGE_SIZE);
```suggestion
        request, file_name, file, page, UNIV_PAGE_SIZE);
```

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +      msg("xtrabackp: error reading first page on file %s\n", file_name);
```suggestion
      msg("xtrabackup: error reading first page on file %s\n", file_name);
```

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +        }
we should abort incremental apply

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +        create new */
```suggestion
        /* space_id of undo tablespace from incremental is different from the full backup. 
        Rename the existing undo tablespace to a temporary name and create undo
        tablespace file with new space_id */
```

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +                 f_space_id);
Use some other convention for undo files. Add undo prefix somewhere

2020-07-30 11:19 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +      /* either file doesn't exists or it has been rename above */
```suggestion
      /* either file doesn't exist or it has been renamed above */
```

2020-08-03 08:31 UTC, satya-bodapati requested changes
LGTM. Few requests
1. Jenkins link here
2.  Which testcase was failing before the patch? Please paste the output of the testcase before and after patch

2020-08-03 08:31 UTC, satya-bodapati commented
@rahulmalik87 Also request to squash all changes into one commit

2020-08-04 11:28 UTC, rahulmalik87 commented
./run.sh -t t/undo_tablespaces.sh -g
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against MySQL 8.0.21 (InnoDB 8.0.21)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
undo_tablespaces                         w1	[passed]    95
==============================================================================
Spent 95 of 101 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-1784.sh
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against MySQL 8.0.21 (InnoDB 8.0.21)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
pxb-1784                                 w1	[passed]    31
==============================================================================
Spent 31 of 36 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output

2020-08-04 11:33 UTC, rahulmalik87 commented
/run.sh -t t/pxb-1784.sh
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against MySQL 8.0.20 (InnoDB 8.0.20)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
pxb-1784                                 w1	[passed]    25
==============================================================================
Spent 25 of 31 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{qa-sm-twina02 x8 o8 test}$./run.sh ^C
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/undo_tablespaces.sh -g
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against MySQL 8.0.20 (InnoDB 8.0.20)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
undo_tablespaces                         w1	[passed]    94
==============================================================================
Spent 94 of 100 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{qa-sm-twina02 x8 o8 test}$

2020-08-04 11:44 UTC, rahulmalik87 commented
./run.sh -t t/undo_tablespaces.sh -g
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against Percona Server 8.0.20-11 (XtraDB 8.0.20-11)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
undo_tablespaces                         w1	[passed]    98
==============================================================================
Spent 98 of 104 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-17
pxb-1700.sh  pxb-1705.sh  pxb-1714.sh  pxb-1784.sh  pxb-1793.sh
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-17
pxb-1700.sh  pxb-1705.sh  pxb-1714.sh  pxb-1784.sh  pxb-1793.sh
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-17
pxb-1700.sh  pxb-1705.sh  pxb-1714.sh  pxb-1784.sh  pxb-1793.sh
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-1784.sh
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against Percona Server 8.0.20-11 (XtraDB 8.0.20-11)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
pxb-1784                                 w1	[passed]    24
==============================================================================
Spent 24 of 30 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output

2020-08-04 11:45 UTC, rahulmalik87 commented
./run.sh -t t/undo_tablespaces.sh -g
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against Percona Server 8.0.20-11 (XtraDB 8.0.20-11)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
undo_tablespaces                         w1	[passed]    98
==============================================================================
Spent 98 of 104 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-17
pxb-1700.sh  pxb-1705.sh  pxb-1714.sh  pxb-1784.sh  pxb-1793.sh
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-17
pxb-1700.sh  pxb-1705.sh  pxb-1714.sh  pxb-1784.sh  pxb-1793.sh
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-17
pxb-1700.sh  pxb-1705.sh  pxb-1714.sh  pxb-1784.sh  pxb-1793.sh
{qa-sm-twina02 x8 o8 test}$./run.sh -t t/pxb-1784.sh
Using /home/rahul.malik/MySQL/src/x8/bld/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against Percona Server 8.0.20-11 (XtraDB 8.0.20-11)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 24
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
pxb-1784                                 w1	[passed]    24
==============================================================================
Spent 24 of 30 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output

2020-08-05 05:12 UTC, satya-bodapati requested changes
Can you paste jenkins link?

Please addresss the review comment and squash merge into single commit.

Close to approval

2020-08-05 05:12 UTC, satya-bodapati commented on storage/innobase/xtrabackup/src/xtrabackup.cc
> +  /* remember space name for further reference */
```suggestion
  /* remember space name used by incremental prepare. This hash is later used to detect
  the dropped tablespaces and remove them. Check rm_if_not_found() */
```

2020-08-05 05:37 UTC, rahulmalik87 commented
m 8.0.21, ps 8.0.20 https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/310/
m 8.0.20, ps 8.0.20 https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/309/

2020-08-05 07:25 UTC, satya-bodapati approved these changes

2020-08-05 07:26 UTC, merged